
name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::430334909132:role/msi-oidc-role
          role-session-name: msi-oidc-role
